### ISSUE TITLE
unicode game paths not working

### ISSUE THREAD

**Issue by ihm-tswow** [wowdev/noggit3#105] opened 2021-10-02 15:14 UTC
Noggit doesn't seem to work when setting game path to a directory containing unicode (windows).

The game path `D:/Загрузки/CircleL/CircleL` gives the following error:

```
10 - (application.cpp:214): Noggit Studio - 3.3354
44 - (application.cpp:239): Game path: "D:/Загрузки/CircleL/CircleL"
45 - (application.cpp:244): Project path: D:/Загрузки/CircleL/CircleL
45 - (application.cpp:120): [Error] Could not find locale directory. Be sure, that there is one containing the file "realmlist.wtf".
```

**Comment by bloerwald** [comment] 2021-10-02 20:10
Duplicate of #65

**Closed as completed** 2021-10-02 20:10 UTC
