### ISSUE TITLE
Script Brushes: model:set_pos() issue

### ISSUE THREAD

**Issue by gratural** [wowdev/noggit3#101] opened 2021-08-13 16:43 UTC
After using model:set_pos(), the model display does not change until you move to another point on the map or restart Noggit. 
Using "Reload tile" creates a instance of the model  (with new ID) and causes an error:

![uid2](https://user-images.githubusercontent.com/3275410/129392071-540ac09c-578c-4cdd-83be-57d5229efe5d.JPG)

![uid3](https://user-images.githubusercontent.com/3275410/129392099-1832b0a2-087a-4134-83df-d0ff2449ec74.JPG)

[0_drop_to_ground2.zip](https://github.com/wowdev/noggit3/files/6983982/0_drop_to_ground2.zip)

**Comment by ihm-tswow** [comment] 2021-08-14 08:36
Can reproduce, think we're missing an update there

**Comment by ihm-tswow** [comment] 2021-08-14 09:34
`model::set_pos`, `model::set_rot` and `model::set_scale` have all been fixed with: 4367f8a54c9b59c86486d2990ab7ea259a525244

The "reload tile" issue seems unrelated because it also happens on earlier non-scripting versions when manually moving models between tiles and reloading. I've asked other devs what's supposed to happen there, moving a model and reloading its tile sounds like undefined behavior to me (isn't that like _asking_ for UID duplication?) but as it might be a bug I'm keeping this issue up until I've heard what they think.

**Comment by gratural** [comment] 2021-08-14 10:50
> Can reproduce, think we're missing an update there

Here is the updated version. Left mouse button and space bar raise the models up, left mouse button and Shift lower them down.
A curious pattern: to update the position of the models, all you have to do is cross the border of another ADT. It's like crossing the Mexican frontier.

[0_drop_to_ground3.zip](https://github.com/wowdev/noggit3/files/6986318/0_drop_to_ground3.zip)

**Comment by ihm-tswow** [comment] 2021-08-14 10:51
Have confirmed reloading a tile after moving a model from it is undefined behavior regardless of doing it manually or with a script. It may be suitable to make a new issue for that, but i'll close this one since it's no longer related to scripting or the set_pos function.

**Closed as completed by ihm-tswow** 2021-08-14 10:51 UTC

**Comment by ihm-tswow** [comment] 2021-08-14 10:53
> > Can reproduce, think we're missing an update there
> 
> Here is the updated version. Left mouse button and space bar raise the models up, left mouse button and Shift lower them down.
> A curious pattern: to update the position of the models, all you have to do is cross the border of another ADT. It's like crossing the Mexican frontier.
> 
> [0_drop_to_ground3.zip](https://github.com/wowdev/noggit3/files/6986318/0_drop_to_ground3.zip)

Oh, I meant the scripting API was missing some updating code, I fixed that with https://github.com/wowdev/noggit3/commit/4367f8a54c9b59c86486d2990ab7ea259a525244 and abbf638f41c78ba2e06b1fa786ce4f4abb0fa44b

With that commit, moving objects works the same as moving them manually.
